name: Integration Test
permissions:
  contents: read
on: workflow_dispatch

jobs:
  current-date:
    name: Get current date for cache
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.cache-version.outputs.cachedate }}
    steps:
      - id: cache-version
        run: echo "cachedate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
  test:
    name: Run test
    needs: current-date
    strategy:
      max-parallel: 1
      matrix:
        node-version: ${{ fromJSON(vars.TEST_NODE_VERSIONS) }}
        os: ${{ fromJSON(vars.TEST_OS_VERSIONS) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "corretto"
          java-version: "11"
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - id: cache-odc-data-dir
        uses: actions/cache@v4
        with:
          enableCrossOsArchive: true
          path: tmp/owasp/data
          key: odc-data-cache-${{needs.current-date.outputs.date}}
          restore-keys: odc-data-cache-
      - run: npm ci
      - run: npm run build
      - run: npm run owasp -- -f HTML
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          OSS_INDEX_USERNAME: ${{ secrets.OSS_INDEX_USERNAME }}
          OSS_INDEX_PASSWORD: ${{ secrets.OSS_INDEX_PASSWORD }}
