name: Publish new release to NPM registry
permissions:
  contents: read
on:
  release:
    types: [created]

jobs:
  validate:
    name: Validate release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.BASE_NODE_VERSION }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run validate-release

  publish-npm:
    name: Publish to NPM
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.BASE_NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  check-published-package:
    name: Check previously published package
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.BASE_NODE_VERSION }}
          cache: "npm"
      - run: npm install -g owasp-dependency-check
      - run: npx owasp-dependency-check --help
      - run: npx owasp-dependency-check --version
