name: run-dependency-check

on: workflow_dispatch

jobs:
  run-dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - id: cache-odc-data-bin
        uses: actions/cache@v4
        with:
          path: |
            dependency-check-data
            dependency-check-bin
          key: dependency-check-cache-${{ github.run_id }}
          restore-keys: |
            dependency-check-cache-
      - run: npm ci
      - run: npm run build
      - run: npm install -g .
      - run: npx owasp-dependency-check --data dependency-check-data -f HTML
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      - id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dependency-check-reports
  deploy-report-on-gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: run-dependency-check
    steps:
      - name: Deploy OWASP report to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
